In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
def ODI_batsmen_rank(url):
    res = requests.get(url)
    soup = BeautifulSoup(res.content, 'html.parser')
    a = soup.find('div', class_ = 'rankings-block__banner--name').text
    b = soup.find('div', class_ = 'rankings-block__banner--nationality').text[2:5]
    c = soup.find('div', class_ = 'rankings-block__banner--rating').text
    

    players = []
    for i in soup.find_all('td', class_ = 'table-body__cell name', limit = 9):
        players.append(i.text.strip('\n'))
    
    
    players.insert(0,a)
   
    team = []
    for i in soup.find_all('span', class_ = 'table-body__logo-text', limit = 9):
        team.append(i.text)
    team.insert(0,b)
    
    rating = []
    for i in soup.find_all('td', class_ = 'table-body__cell u-text-right rating', limit = 9):
        rating.append(i.text)
    rating.insert(0,c)
    ind = []
    for i in range(1,11):
        ind.append(i)
    odi_batsmen_ranking = pd.DataFrame({'Player': players, 'Team': team, 'Ratings': rating}, index = ind)
    return odi_batsmen_ranking

In [3]:
url = 'https://www.icc-cricket.com/rankings/mens/player-rankings/odi'
odi_batsmen_ranking = ODI_batsmen_rank(url)
odi_batsmen_ranking

                   Player Team Ratings
1              Babar Azam  PAK     887
2   Rassie van der Dussen   SA     777
3             Imam-ul-Haq  PAK     740
4         Quinton de Kock   SA     740
5            Shubman Gill  IND     738
6            David Warner  AUS     726
7             Virat Kohli  IND     719
8            Rohit Sharma  IND     707
9             Steve Smith  AUS     702
10           Fakhar Zaman  PAK     699