In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
def team_rank(url):
    res = requests.get(url)
    soup = BeautifulSoup(res.content, 'html.parser')
    mathces_and_points = []
    for i in soup.find_all('td', class_ = 'table-body__cell u-center-text', limit = 18):
        mathces_and_points.append(i.text)

    matches = []
    points = []
    for (i,item) in enumerate(mathces_and_points):
        if i%2==0:
            matches.append(item)
        else:
            points.append(item)

    b = soup.find('td', class_ = 'rankings-block__banner--matches').text
    c = soup.find('td', class_ = 'rankings-block__banner--points').text

    matches.insert(0,b)

    points.insert(0,c)




    odi = []
    for i in soup.find_all('span', class_ = 'u-hide-phablet', limit = 10):
        odi.append(i.text)

    a = soup.find('td', class_ = 'rankings-block__banner--rating u-text-right').text[29:32]
    ratings = []
    for i in soup.find_all('td', class_ = 'table-body__cell u-text-right rating', limit = 9):
        ratings.append(i.text)
    ratings.insert(0,a)
    
    ind = []
    for i in range(1,11):
        ind.append(i)

    team_rankings = pd.DataFrame({'Team':odi, 'Matches': matches, 'Points': points, 'Ratings': ratings}, index = ind)
    
    return team_rankings

In [3]:
url = 'https://www.icc-cricket.com/rankings/womens/team-rankings/odi'
Team_rankings = team_rank(url)
Team_rankings

            Team Matches Points Ratings
1      Australia      21  3,603     172
2        England      28  3,342     119
3   South Africa      26  3,098     119
4          India      27  2,820     104
5    New Zealand      25  2,553     102
6    West Indies      27  2,535      94
7     Bangladesh      13    983      76
8       Thailand       8    572      72
9       Pakistan      27  1,678      62
10     Sri Lanka       8    353      44